# Generated by Django 4.2.3 on 2023-07-09 14:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='organisation',
            new_name='organization',
        ),
        migrations.AddField(
            model_name='user',
            name='auth_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='First authentification date'),
            preserve_default=False,
        ),
    ]
