# Generated by Django 4.2.3 on 2023-07-09 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_organisation_user_organization_user_auth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='auth_date',
        ),
    ]
