# Generated by Django 4.2.3 on 2023-07-09 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_user_auth_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='auth_time',
        ),
    ]
