# Generated by Django 4.2.3 on 2023-07-10 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_rename_fist_name_user_first_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
