# Generated by Django 3.2.20 on 2023-07-19 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_remove_user_password'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
